In [22]:
import numpy
matrix1 = numpy.array([[2,0,-3],[1,4,0],])
matrix2 = numpy.array([[1,2],[2,1],[1,2],])

In [23]:
print(matrix1)
print(matrix2)


[[ 2  0 -3]
 [ 1  4  0]]
[[1 2]
 [2 1]
 [1 2]]


In [25]:
result = numpy.dot(matrix1,matrix2)

print(result)

[[-1 -2]
 [ 9  6]]


In [26]:
hello = numpy.argmax(matrix1)
print(hello)

4
