In [20]:
import numpy
matrix1 = numpy.array([[3,5,7,0,-3,-5],[2,4,6,8,-2,-4],])
matrix2 = numpy.array([[11,10,22,20],[1,2,3,4],[9,8,7,6],])
matrix3 = numpy.array([[1,1,0],[2,2,0],[3,3,3],[-4,4,4],[5,6,7],[2,4,8],])

In [21]:
result = numpy.dot(matrix1,matrix3)
insult = numpy.dot(matrix3,matrix2)


In [22]:
print(result)
print(insult)


[[  9  -4 -40]
 [-22  32   4]]
[[ 12  12  25  24]
 [ 24  24  50  48]
 [ 63  60  96  90]
 [ -4   0 -48 -40]
 [124 118 177 166]
 [ 98  92 112 104]]
